### ISSUE TITLE
43页最上面两段顺序颠倒～

### ISSUE THREAD

**Issue by xgbgyn** [PengFoo/deep-learning-cn#3]
翻译的很好，赞一个

**Comment by PengFoo** [comment]
hi，官方的翻译repo已经翻译完成而且出版成书。
本项目自bengio告知版权已交给中方处理后已经停止更新啦，详情请参见官方repo（也是有免费PDF全本可供下载的）
https://github.com/exacity/deeplearningbook-chinese

最后感谢您的悉心阅读！
